version: '3.3'
services:
  utility:
    container_name: ansible
    build: ./
    image: local/ansible:1.0
    volumes:
      - ./:/opt/
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "FALSE"
    env_file: .env
    command: tail -f /dev/null
    working_dir: /opt