---
- hosts: web
  become: yes 
  vars:
    docker_edition: 'ce'
    docker_install_compose: true
  
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get update && apt-get -y install python-simplejson
      
  roles:
  - geerlingguy.pip
  - geerlingguy.docker
  - geerlingguy.git
  
  tasks:
  - name: test docker version
    raw: docker --version
  
  - name: test docker-compose version
    raw: docker-compose --version
    
  - name: Clone git repo
    git:
      repo: "https://github.com/melissapalmer/openapi-generator-cli.git"
      dest: "/gitrepo"
      version: "master"
      force: true
      accept_hostkey: true
      
      